# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phoneNo', models.CharField(max_length=20)),
                ('diet', models.CharField(max_length=10)),
                ('medNo', models.CharField(max_length=10)),
                ('practAd', models.CharField(max_length=50)),
            ],
        ),
    ]
