# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phoneNo',
            field=models.IntegerField(),
        ),
    ]
