# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160922_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phoneNo',
            field=models.CharField(max_length=15),
        ),
    ]
